name: Push CrisperWhisper COG to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'nyrahealth/CrisperWhisper'
  push:
    branches:
      - main

jobs:
  push_to_replicate:
    name: Push CrisperWhisper to Replicate
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}
      - name: Push to Replicate
        run: cog push r8.im/primeinc/crisperwhisper
